import '../app/globals.css'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'myTaskList, made with Next.js',
  description: 'Created by Danyal Imran and generated by Next.js ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
          {children}
        <Footer />
        </body>
    </html>
  )
}
